title: Open Source by Tonk√ºnstler-on-the-Bund
author:
  type: Organization
  name: TKB
  url: https://www.tonkunstler-on-the-bund.com
locale: en_GB
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
incremental: true
exclude: [assets/, !assets/js/, supplement.csv, csv-to-md.py, csv_tools.py, LICENSE]
